name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up the SSH key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Install dependencies on the EC2 instance
      - name: Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@98.81.144.14 sudo apt update

      # Install Node.js on the EC2 instance
      - name: Install Node.js
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@98.81.144.14 'curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs'

      # Create the destination directory on EC2
      - name: Create destination directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@98.81.144.14 'sudo mkdir -p /home/ubuntu/medusa-gitaction && sudo chown ubuntu:ubuntu /home/ubuntu/medusa-gitaction'

      # Use rsync to copy project files to EC2, excluding node_modules and logs
      - name: Copy project files to EC2 with rsync
        run: |
          rsync -avz --exclude 'node_modules' --exclude 'logs' ./ ubuntu@98.81.144.14:/home/ubuntu/medusa-gitaction/

      # Install project dependencies inside a tmux session and restart Medusa
      - name: Install dependencies and restart Medusa on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@98.81.144.14 'tmux new -d -s medusa_session "cd /home/ubuntu/medusa-gitaction && NODE_OPTIONS=\"--max-old-space-size=4096\" npm install && pm2 restart medusa"'
